# Copyright (c) 2024, Silex Data Solutions <info@silexdata.com>
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-FileCopyrightText: 2024 Silex Data Solutions <info@silexdata.com>
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = '''
---
name: cisco_meraki
version_added: "1.0.0"
requirements:
  - meraki >= 1.33.0
short_description: Uses Cisco Meraki API as an inventory source.
description:
  - Get inventory hosts from Meraki API.
notes:
  - If you want to set vars for the C(all) group inside the inventory file, the C(all) group must be the first entry in the file.
  - Enabled in configuration by default.
extends_documentation_fragment:
  - inventory_cache
  - constructed
options:
  plugin:
    description: token that ensures this is a source file for the C(cisco_meraki) plugin.
    required: true
    choices: ['silexdata.meraki.cisco_meraki']
  meraki_base_url:
    description:
      - URL of the Meraki API
    default: https://api.meraki.com/api/v1
  meraki_api_key:
    description:
      - Token created for the Meraki API
    required: true
    env:
      - name: MERAKI_DASHBOARD_API_KEY
  group_prefix:
    description:
      - Prefix for group names generated by the plugin via C(want_*) options.
    required: false
    default: net_meraki_
  group_parent:
    description:
      - Parent group for other groups generated by the plugin via C(want_*) options.
    required: false
  want_devices:
    description:
      - Toggle, if true the inventory will fetch the devices belonging to each network. This can take a long time, so it is disabled by default.
    type: boolean
    default: false
  want_organization:
    description:
      - Toggle, if true the inventory will fetch the organization the network belongs to and create groups for the same using C(group_prefix) if defined
    type: boolean
    default: true
'''

from ansible.errors import AnsibleError
from ansible.module_utils.basic import missing_required_lib
from ansible.plugins.inventory import BaseInventoryPlugin, Cacheable, Constructable, to_safe_group_name

try:
    import meraki
except ImportError:
    HAS_MERAKI = False
else:
    HAS_MERAKI = True


class InventoryModule(BaseInventoryPlugin, Cacheable, Constructable):
    '''Host inventory parser for ansible using Cisco Meraki API as source'''

    NAME = 'silexdata.meraki.cisco_meraki'

    def __init__(self):
        super().__init__()

        self.group_parent = None
        self.group_prefix = None

    def verify_file(self, path):
        valid = False
        if super().verify_file(path):
            if path.endswith(('meraki.yaml', 'meraki.yml')):
                valid = True
            else:
                self.display.vvv('Skipping due to inventory source not ending in "meraki.yaml" nor "meraki.yml"')
        return valid

    def add_host(self, hostname, host_vars):
        self.inventory.add_host(hostname)

        for var_name, var_value in host_vars.items():
            self.inventory.set_variable(hostname, var_name, var_value)

        strict = self.get_option('strict')

        # Add variables created by the user's Jinja2 expressions to the host
        self._set_composite_vars(self.get_option('compose'), host_vars, hostname, strict=strict)

        # Create user-defined groups using variables and Jinja2 conditionals
        self._add_host_to_composed_groups(self.get_option('groups'), host_vars, hostname, strict=strict)
        self._add_host_to_keyed_groups(self.get_option('keyed_groups'), host_vars, hostname, strict=strict)

    def _fetch_organizations(self):
        '''Read every organization, its networks and, if wanted, their devices from the Meraki API'''
        if not HAS_MERAKI:
            raise AnsibleError(missing_required_lib('meraki'))

        base_url = self.get_option('meraki_base_url')
        want_devices = self.get_option('want_devices')
        try:
            dashboard = meraki.DashboardAPI(
                api_key=self.get_option('meraki_api_key'),
                base_url=base_url,
                suppress_logging=True,
            )
            organizations = []
            # The SDK returns one page unless asked for all of them.
            for org in dashboard.organizations.getOrganizations(total_pages='all'):
                networks = dashboard.organizations.getOrganizationNetworks(org['id'], total_pages='all')
                if want_devices:
                    for network in networks:
                        network['devices'] = dashboard.networks.getNetworkDevices(network['id'])
                organizations.append({'id': org['id'], 'name': org['name'], 'networks': networks})
        except Exception as e:
            raise AnsibleError(f'Unable to read the inventory from the Meraki API at {base_url}: {e}') from e
        return organizations

    def _populate(self, organizations):
        self.group_parent = self.get_option('group_parent')
        self.group_prefix = self.get_option('group_prefix')
        want_devices = self.get_option('want_devices')
        want_organization = self.get_option('want_organization')

        # Create parent group (if defined)
        if self.group_parent:
            self.inventory.add_group(self.group_parent)

        for org in organizations:
            # Create a group for the organization if desired
            if want_organization:
                org_group_name = to_safe_group_name(f"{self.group_prefix}organization_{org['name'].lower().replace(' ', '')}")
                self.inventory.add_group(org_group_name)
                if self.group_parent:
                    self.inventory.add_child(self.group_parent, org_group_name)

            for network in org['networks']:
                host_vars = {
                    'ansible_connection': 'local',
                    'id': network['id'],
                    'product_types': network['productTypes'],
                    'tags': network['tags'],
                    'time_zone': network['timeZone'],
                    'enrollment_string': network['enrollmentString'],
                    'notes': network['notes'],
                    'url': network['url'],
                    'is_bound_to_config_template': network['isBoundToConfigTemplate'],
                    'org_id': org['id'],
                    'org_name': org['name'],
                }

                if want_devices:
                    host_vars['devices'] = network.get('devices', [])

                self.add_host(network['name'], host_vars)

                if want_organization:
                    self.inventory.add_child(org_group_name, network['name'])

    def parse(self, inventory, loader, path, cache=True):
        super().parse(inventory, loader, path)

        # Read config from file
        self._read_config_data(path)

        # Serve the API data from the inventory cache when it is enabled and
        # holds this source; otherwise read it, and cache it if enabled.
        cache_key = self.get_cache_key(path)
        user_cache_setting = self.get_option('cache')
        attempt_to_read_cache = user_cache_setting and cache
        cache_needs_update = user_cache_setting and not cache

        organizations = None
        if attempt_to_read_cache:
            try:
                organizations = self._cache[cache_key]
            except KeyError:
                cache_needs_update = True

        if organizations is None:
            organizations = self._fetch_organizations()

        if cache_needs_update:
            self._cache[cache_key] = organizations

        # Populate the inventory
        self._populate(organizations)
