# Copyright (c) 2024, Silex Data Solutions <info@silexdata.com>
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-FileCopyrightText: 2024 Silex Data Solutions <info@silexdata.com>
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = '''
---
name: cisco_meraki
version_added: "1.0.0"
requirements:
  - meraki >= 1.33.0
short_description: Uses Cisco Meraki API as an inventory source.
description:
  - Get inventory hosts from Meraki API.
notes:
  - If you want to set vars for the C(all) group inside the inventory file, the C(all) group must be the first entry in the file.
  - Enabled in configuration by default.
extends_documentation_fragment:
  - inventory_cache
  - constructed
options:
  plugin:
    description: token that ensures this is a source file for the C(cisco_meraki) plugin.
    required: true
    choices: ['silexdata.meraki.cisco_meraki']
  meraki_base_url:
    description:
      - URL of the Meraki API
    default: https://api.meraki.com/api/v1
  meraki_api_key:
    description:
      - Token created for the Meraki API
    required: true
    env:
      - name: MERAKI_DASHBOARD_API_KEY
  group_prefix:
    description:
      - Prefix for group names generated by the plugin via C(want_*) options.
    required: false
    default: net_meraki_
  group_parent:
    description:
      - Parent group for other groups generated by the plugin via C(want_*) options.
    required: false
  want_devices:
    description:
      - Toggle, if true the inventory will fetch the devices belonging to each network. This can take a long time, so it is disabled by default.
    type: boolean
    default: false
  want_organization:
    description:
      - Toggle, if true the inventory will fetch the organization the network belongs to and create groups for the same using C(group_prefix) if defined
    type: boolean
    default: true
'''

from ansible.errors import AnsibleError
from ansible.module_utils.basic import missing_required_lib
from ansible.plugins.inventory import BaseInventoryPlugin, Cacheable, Constructable, to_safe_group_name

try:
    import meraki
except ImportError:
    HAS_MERAKI = False
else:
    HAS_MERAKI = True


class InventoryModule(BaseInventoryPlugin, Cacheable, Constructable):
    '''Host inventory parser for ansible using Cisco Meraki API as source'''

    NAME = 'silexdata.meraki.cisco_meraki'

    def __init__(self):
        super().__init__()

        self.dashboard = None
        self.group_parent = None
        self.group_prefix = None

    def verify_file(self, path):
        valid = False
        if super().verify_file(path):
            if path.endswith(('meraki.yaml', 'meraki.yml')):
                valid = True
            else:
                self.display.vvv('Skipping due to inventory source not ending in "meraki.yaml" nor "meraki.yml"')
        return valid

    def add_host(self, hostname, host_vars):
        self.inventory.add_host(hostname)

        for var_name, var_value in host_vars.items():
            self.inventory.set_variable(hostname, var_name, var_value)

        strict = self.get_option('strict')

        # Add variables created by the user's Jinja2 expressions to the host
        self._set_composite_vars(self.get_option('compose'), host_vars, hostname, strict=True)

        # Create user-defined groups using variables and Jinja2 conditionals
        self._add_host_to_composed_groups(self.get_option('groups'), host_vars, hostname, strict=strict)
        self._add_host_to_keyed_groups(self.get_option('keyed_groups'), host_vars, hostname, strict=strict)

    def _populate(self):
        self.groups = dict()
        self.hosts = dict()
        self.group_parent = self.get_option('group_parent')
        self.group_prefix = self.get_option('group_prefix')
        self.want_devices = self.get_option('want_devices')
        self.want_organization = self.get_option('want_organization')

        # Create parent group (if defined)
        if self.group_parent:
            self.inventory.add_group(self.group_parent)

        orgs = self.dashboard.organizations.getOrganizations()

        for org in orgs:
            networks = self.dashboard.organizations.getOrganizationNetworks(org['id'])

            # Create a group for the organization if desired
            if self.want_organization:
                org_group_name = to_safe_group_name(f"{self.group_prefix}organization_{org['name'].lower().replace(' ', '')}")
                self.inventory.add_group(org_group_name)
                if self.group_parent:
                    self.inventory.add_child(self.group_parent, org_group_name)

            for network in networks:
                host_vars = {
                    'ansible_connection': 'local',
                    'id': network['id'],
                    'product_types': network['productTypes'],
                    'tags': network['tags'],
                    'time_zone': network['timeZone'],
                    'enrollment_string': network['enrollmentString'],
                    'notes': network['notes'],
                    'url': network['url'],
                    'is_bound_to_config_template': network['isBoundToConfigTemplate'],
                    'org_id': org['id'],
                    'org_name': org['name'],
                }

                if self.want_devices:
                    devices = self.dashboard.networks.getNetworkDevices(network['id'])
                    host_vars.update({'devices': devices})

                self.add_host(network['name'], host_vars)

                if self.want_organization:
                    self.inventory.add_child(org_group_name, network['name'])

    def parse(self, inventory, loader, path, cache=True):
        super().parse(inventory, loader, path)

        # Read config from file
        self._read_config_data(path)

        if not HAS_MERAKI:
            raise AnsibleError(missing_required_lib('meraki'))

        self.dashboard = meraki.DashboardAPI(suppress_logging=True)

        # Populate the inventory
        self._populate()
